### ISSUE TITLE
Sai sót tại trang Giới thiệu: /src/v2/guide/index.md

### ISSUE THREAD

**Issue by dthphuong** [vuejs-vn/vuejs.org#72]
Trong lúc tìm hiểu về Vue.JS và làm qua thử các ví dụ ban đầu thì mình phát hiện có một sai sót nhỏ tại mục **Giới thiệu / Xử lý thông tin đầu vào của người dùng**. 

Đoạn code mẫu: 
```HTML
<div id="app-6">
   <p>{{ message }}</p>
   <input v-model="message">
   <button v-on:click="changeMessage">Thay đổi thông điệp</button>
</div>
```

Đoạn code đúng cần chỉnh sửa: 
```HTML
<div id="app-6">
   <p>{{ message }}</p>
   <input v-model="message">
</div>
```

Mong @phanan xem và update cho các bạn khác nhé !

**Comment by phanan** [comment]
👍
