### ISSUE TITLE
Instance nên dịch lại thành "thực thể"

### ISSUE THREAD

**Issue by IHNEL** [vuejs-vn/vuejs.org#84]
Ý kiến cá nhân, tôi nghĩ "instance" nên dịch thành "thực thể" sẽ hợp lý hơn.

**Comment by tatthien** [comment]
Theo mình không thể dịch `Instance` thành `Thực Thể` được. Nếu bạn dịch `Entity` là `Thực Thể` thì hợp lí.

- `Entity/Thực Thể` liên quan đến database.
- `Instance` có thể hiểu là liên quan class, ở đây là Vue.

Refs:
https://wikidiff.com/instance/entity
https://stackoverflow.com/questions/20461907/what-is-meaning-of-instance-in-programming

**Comment by tatthien** [comment]
Ping @IHNEL

**Comment by IHNEL** [comment]
Trong trường hợp Vue, khi xem Vue là 1 class thì 1 instance của class này nên được hiểu chính xác là 1 thực thể của class đó.
Tôi thấy câu trả lời trong link stackoverflow bạn đính kèm ở trên là rất chính xác và phù hợp trong trường hợp của Vue Instance:

> "instance" is best understood as it relates to "class" in programming. "Classes" are used to define the properties and behavior of a category of things. E.g. A "Car" class might dictate that all cars be defined by their make, model, year, and mileage.

Không nên bó buộc `instance` chỉ được dùng cho các diễn giải liên quan tới database.  Có thể ánh xạ về mặt ý nghĩa, 1 table trong database là 1 class (vì nó định nghĩa các colume/property mà nó chứa bên trong), thì mỗi 1  dòng  dữ liệu tương ứng với 1  instance.

**Comment by namdau** [comment]
Thank you for your contribution but unfortunately we'll gonna archive this repo in favor of the official v3 documentation which is being forked here https://github.com/vuejs-vn/docs-next.

**Comment by namdau** [comment]
Close this one in favor of adapting [v3 doc repo ](https://github.com/vuejs-vn/docs-next).
